### ISSUE TITLE
Input error during stream

### ISSUE THREAD

**Issue by javiherbar33** [catid/CauchyCaterpillar#2]
Hi!

I've been testing the library on some tiny projects, it worked like a charm! I was able to recover lost packets as expected. 

When I moved it to a bigger project (real time video streaming) I noticed the library fails after successfully decoding ~200 packets. 

Library returns error code 1, but after checking input I don't seem to find the root of the problem. 

Any Ideas where to look at?

Thanks in advance, 
congratulations on your work, the library is really useful.
Javier.

**Comment by catid** [comment]
That looks like “invalid input” error.  I can help you Debug if I see a
repro.  Maybe check that the inputs are not out of range or null

**Comment by javiherbar33** [comment]
I'm getting the error when decoding a recovery packet, and when logging input, it seems to be valid and not null. 

System is working on 30 FPS, sending arround 300 packets (1400 bytes) per second.

FEC rate is 1 recovery every 3 originals.

Unfortunately i cannot show you code, I will look more closely into input to check if the're always in range. 

Thanks!.

**Comment by catid** [comment]
If you are using MSVC then you can break in the debugger when it returns 1
and then click and drag the instruction cursor back above the call to run
through it again and see what causes it

**Comment by catid** [comment]
Or could set a breakpoint in that error case in the codec

**Comment by catid** [comment]
Any luck?

**Comment by javiherbar33** [comment]
No, but i'm still following the idea of unvalid input data. 

I believe for some reason the RecoveryRow field of the critic recovery packet is causing the failure.  

Little progress so far, but I firmly believe the error is in the way I'm handling data, and it's not a library-related error. 

Thanks a lot for your help!

Keep up with your great work,

Javier.
